import type { Metadata } from "next";
import { Inter, Rock_Salt } from "next/font/google";
import "./globals.css";

export const inter = Inter({ subsets: ["latin"] });
export const rockSalt = Rock_Salt({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
